# Generated by Django 3.2.13 on 2022-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosyal_medya_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='begeni_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
