# Generated by Django 3.2.13 on 2022-08-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosyal_medya_app', '0004_post_begeni_sayisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='begeni_sayisi',
        ),
    ]
